### ISSUE TITLE
Missing SQL column types

### ISSUE THREAD

**Issue by BrianGreenhill** [watoki/stores#1]
Currently it's not possible to add a field type of LONGTEXT for example.

The problem with taking the types out of the doc comments is that I would have to write an invalid @var type in order to get all possible SQL Column types. It would be easier to be able to set the field type for each object property.

**Comment by rtens** [comment]
It won't be possible to do that with the automatic table creation. But maybe the default type should be long text.

**Comment by rtens** [comment]
Deprecated with new design
