### ISSUE TITLE
Unclear exception caused by Entity Identifier not being named identically to Entity

### ISSUE THREAD

**Issue by BrianGreenhill** [watoki/stores#2]
Error:
Uncaught exception 'Exception' with message 'Unknown type [].'

**Comment by rtens** [comment]
How can I reproduce this exception?

**Comment by BrianGreenhill** [comment]
1. Create an Identifer Class called EntityId.
2. Create an Entity called NewEntity
3. Typehint the Identifier Class in the parameters of the constructor of
   the entity
4. At this point I tried to load my index resource in the browser and
   received the Exception.

2015-03-17 18:16 GMT+01:00 Nikolas Martens notifications@github.com:

**Comment by rtens** [comment]
Removed IdentifierType
